core:
  xmin: -2.0
  xmax: 1.0
  ymin: -1.5
  ymax: 1.5
  width: 30
  height: 30
  max_iter: 50
  representation_size: 4
  message_passing_alpha: 0.5
  vram_limit_mb: 0.5
  ram_limit_mb: 1.0
  disk_limit_mb: 10
  file_tier_path: "data/marble_file_tier.dat"
  init_noise_std: 0.0
  default_growth_tier: "vram"
neuronenblitz:
  backtrack_probability: 0.3
  consolidation_probability: 0.2
  consolidation_strength: 1.1
  route_potential_increase: 0.5
  route_potential_decay: 0.9
  route_visit_decay_interval: 10
  alternative_connection_prob: 0.1
  split_probability: 0.2
  merge_tolerance: 0.01
  plasticity_threshold: 10.0
  continue_decay_rate: 0.85
  struct_weight_multiplier1: 1.5
  struct_weight_multiplier2: 1.2
  attention_decay: 0.9
  max_wander_depth: 100
  learning_rate: 0.01
  structural_plasticity_enabled: true
  backtrack_enabled: true
  loss_scale: 1.0
  exploration_bonus: 0.0
  synapse_potential_cap: 100.0
  attention_update_scale: 1.0
brain:
  save_threshold: 0.05
  max_saved_models: 5
  save_dir: "saved_models"
  firing_interval_ms: 500
  initial_neurogenesis_factor: 1.0
  offload_enabled: false
  torrent_offload_enabled: false
  mutation_rate: 0.01
  mutation_strength: 0.05
  prune_threshold: 0.01
  dream_num_cycles: 10
  dream_interval: 5
  neurogenesis_base_neurons: 5
  neurogenesis_base_synapses: 10
  offload_threshold: 1.0
  torrent_offload_threshold: 1.0
  cluster_high_threshold: 1.0
  cluster_medium_threshold: 0.1
  dream_synapse_decay: 0.995
  neurogenesis_increase_step: 0.1
  neurogenesis_decrease_step: 0.05
  max_neurogenesis_factor: 3.0
  cluster_k: 3
  auto_save_interval: 5
  auto_firing_enabled: false
  dream_enabled: true
  vram_age_threshold: 300
  ram_age_threshold: 600
  status_display_interval: 0
  neurogenesis_interval: 1
  min_cluster_size: 1
  prune_frequency: 1
  auto_offload: false
  benchmark_enabled: false
  tier_decision_params:
    vram_usage_threshold: 0.9
    ram_usage_threshold: 0.9
formula: "log(1+T)/log(1+I)"
formula_num_neurons: 100
meta_controller:
  history_length: 5
  adjustment: 0.5
  min_threshold: 1.0
  max_threshold: 20.0
neuromodulatory_system:
  initial:
    arousal: 0.0
    stress: 0.0
    reward: 0.0
    emotion: "neutral"
memory_system:
  long_term_path: "long_term_memory.pkl"
  threshold: 0.5
  consolidation_interval: 10
remote_client:
  url: "http://localhost:8001"
  timeout: 5.0
  max_retries: 3
torrent_client:
  client_id: "main"
  buffer_size: 10
  heartbeat_interval: 30
data_compressor:
  compression_level: 6
  compression_enabled: true
