dataset:
  num_shards: 1
  shard_index: 0
  offline: false
logging:
  structured: false
  log_file: run.log
  level: "INFO"
  format: "%(levelname)s:%(name)s:%(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
  propagate: false
  rotate: false
  max_bytes: 1048576
  backup_count: 5
  encoding: "utf-8"

attention_codelets:
  enabled: true
  coalition_size: 2
