name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pre-commit
        run: pre-commit run --files $(git diff --name-only HEAD)
      - name: Check unused config keys
        run: |
          python scripts/list_config_keys.py config.yaml --unused --report unused_config_keys.txt
          git diff --exit-code unused_config_keys.txt
      - name: Run tests
        run: pytest -n auto
